### ISSUE TITLE
ResponseCode for unknown devices shall not be 404

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NetworkDataLakeProxy#20]
In v1.0.0 spec and test responseCode 404 should be returned if the device provided in the requestBody is not found.
BUT: 404 is only applicable to invalid URLs, not invalid requestBody data.

Therefore, 404 is wrong.
A final decision on what to use has not been agreed upon (should be harmonized across apps).
A possible responseCode would be 400.

**Comment by openBackhaul** [comment]
My proposal:
If the mountName provided in the requestBody would not be contained in the list of connected devices : 460
If the mountName could be found in the list of connected devices, but MWDI does not provide data for it : 530
Reference to [List of internally defined response codes](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/HowToDefineErrorMessages/HowToDefineErrorMessages.md#list-of-internally-defined-response-codes)

Issue to be solved as a part of dealing with issue #21

**Comment by openBackhaul** [comment]
My proposal:
If the mountName provided in the requestBody would not be contained in the list of connected devices : 460
If the mountName would be listed, but MWDI doesn't provide data : 530
Please see [List of internally defined response codes](https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/SpecifyingApplications/HowToDefineErrorMessages/HowToDefineErrorMessages.md#list-of-internally-defined-response-codes)

**Comment by kmohr-soprasteria** [comment]
changes in OAS already done with changes for #21, but testcases still need to be adapted.
The testcase for unknown device must be changed for 530.

![image](https://github.com/user-attachments/assets/7cc7174e-e9e1-46a9-a3bd-84fb2ccee664)

We can only properly test 530, because to test 460 we would need to find a device, which is in the deviceList but does not deliver data first and for that we would at max need to query all devices and hopefully would end up with a candidate device.

**Comment by kmohr-soprasteria** [comment]
- new responseCodes should be added to the spec - handled with #21
- the testcase collection from v1.0.0 will be replaced by the simulator #27 

therefore, issue closed
