### ISSUE TITLE
Specification v1.0.0 - Requirement for Caching unclear

### ISSUE THREAD

**Issue by paulBMentopolis** [openBackhaul/NetworkDataLakeProxy#22]
In the README description for NDLP, it is mentioned that the data which is provided as response by the individual services is not required to be real-time.

"The following performance criteria shall be kept:
    - No real-time data required (Information to be taken from MWDI)
    - Retrieval of the data at least once a day
    - ...
"

In the diagrams, there is no mention of a local cache like for example an elastic-search instance.

Could you clarify if there is a requirement for local caching of MWDI data?

**Comment by openBackhaul** [comment]
There is no local caching required in the NDLP.
It is passing the requests from NDL to MWDI and the responses vice versa.
