### ISSUE TITLE
Clarification required in the data structure of the "FILTERED_CONTROL_CONSTRUCT"

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/NetworkDataLakeProxy#23]
As per the specification , FILTERED_CONTROL_CONSTRUCT(response body of /v1/provide-inventory-of-device) schema has the following properties included , 
```
1. profile-collection
2. equipment-augment-1-0:control-construct-pac
3. equipment
4. forwarding-domain
5. logical-termination-point
6. top-level-equipment
7. firmware-1-0:firmware-collection
```
In the schema definition of FILTERED_CONTROL_CONSTRUCT , there is no required attributes defined + by default, the additionalProperties is true.

Does it mean , the filtered control construct 
- shall/shall not have the above mentioned properties
- shall have additional properties.

Kindly please clarify.

**Comment by kmohr-soprasteria** [comment]
It shall have the properties.
the required property needs to be added with v1.0.1_spec (see #25)

**Comment by openBackhaul** [comment]
Katharina is right for service paths and their responseBodies.
In this particular case, I would like to stick with the concept of MWDI and MDIP.
Incomplete and wrong responses shall be given, but not suppressed.
Means: The NDLP shall provide whatever is stored in and answered by the MWDI.
=> No required: and no additionalProperties=false statements.

**Comment by PrathibaJee** [comment]
Thank you both for the clarification.

>  The NDLP shall provide whatever is stored in and answered by the MWDI
>  => No required: and no additionalProperties=false statements.
This is clear and if you are fine I will close this issue.
