### ISSUE TITLE
Add >required< statements to requestBodies/responseBodies where missing

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NetworkDataLakeProxy#25]
required statements should be included in the response bodies, with exception of the callbacks.

**Comment by openBackhaul** [comment]
Is to be checked, whether the required: statements are actually missing.
Searching shall be limited to service paths (but not resource paths).

**Comment by kmohr-soprasteria** [comment]
nothing to be done for both individual services
