### ISSUE TITLE
provideInventoryOfDevice URL mismatch

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/NetworkDataLakeProxy#33]
While testing the NDLP we found a mismatch between the NDLP OAS and the Postman test collection. 
In the specification, the provideInventoryOfDevice service is specified with the URL /v1/provide-inventory-of-device.
In the Postman Collection and Mockoon file, however, it is: /v1/provide-inventory-data-of-device.
We currently use /v1/provide-inventory-data-of-device in the NDLP implementation.
Which of the two URLs should we use?

**Comment by ThomasSeitz** [comment]
I asked Katharina for a recommentation.

**Comment by ThomasSeitz** [comment]
We stick to the URL from OAS:       /v1/provide-inventory-of-device

Who is the owener of  the Postman Collection and Mockoon file? There it has to be changed.

**Comment by ThomasSeitz** [comment]
Postman Collection und Mockoon File wird von TEF betreut.
! wird erstetzt durch Simulator mit neuer Testcase Collection ersetzt

**Comment by MFMentopolis** [comment]
We switched to /v1/provide-inventory-of-device, like in the original spec:

https://github.com/openBackhaul/NetworkDataLakeProxy/commit/a092a0c8642b4ccacf7af306ca3565dd71361b58
