### ISSUE TITLE
Clarification of the /v1/provide-inventory-data-of-device filtering

### ISSUE THREAD

**Issue by MFMentopolis** [openBackhaul/NetworkDataLakeProxy#47]
Issues #39, #40, #41, #42, #43 showed it is currently not clear, how the /v1/provide-inventory-data-of-device response data should be filtered concrete.

The response schema "inline_response_200_1" contained in the OAS contains various "additionalProperties: true" options, allowing any additional data, for example:

    FILTERED_CONTROL_CONSTRUCT:
      type: object
      properties:
        profile-collection:
          type: object
          additionalProperties: true
        equipment-augment-1-0:control-construct-pac:
          type: object
          additionalProperties: true

...

    LAYER_PROTOCOL:
      additionalProperties: true
      oneOf:
      - type: object
        properties:
          local-id:
            type: string
          layer-protocol-name:
            type: string
            enum:
            - air-interface-2-0:LAYER_PROTOCOL_NAME_TYPE_AIR_LAYER
          air-interface-2-0:air-interface-pac:
            $ref: '#/components/schemas/LAYER_PROTOCOL_airinterface20airinterfacepac'
        description: air-interface

This leads to the fact, this example from #39 of a data subset including a clearing threshold alarm list is currently valid when using the schema for validation:

    {
      "uuid": "LTP-PURE-TTP-4-4",
      "layer-protocol": [
        {
          "pure-ethernet-structure-2-0:pure-ethernet-structure-pac": {
            "pure-ethernet-structure-configuration": {
              "g-826-threshold-cross-alarm-list": [
                {
                  "alarm-raising-threshold": -1,
                  "g-826-value-kind": "pure-ethernet-structure-2-0:G_826_TYPE_NOT_SPECIFIED",
                  "granularity-period": "pure-ethernet-structure-2-0:GRANULARITY_PERIOD_TYPE_NOT_YET_DEFINED",
                  "alarm-clearing-threshold": -1
                }
              ],
              "performance-monitoring-is-on": true
            }
          },
          "local-id": "LP-PURE-TTP-4-4",
          "layer-protocol-name": "pure-ethernet-structure-2-0:LAYER_PROTOCOL_NAME_TYPE_PURE_ETHERNET_STRUCTURE_LAYER"
        }
      ]
    }

**Comment by kmohr-soprasteria** [comment]
As a side note, note that per default, if not mentioned additionalProperties is true anyways. But if I remember correctly, it had to be added here explicitly there was an error in the schema indicated (if I remember correctly the error was in Postman, not in VSC).

If NDLP receives data from the MWDI that is valid according to the NDLP schema, it shall be accepted. The related schema(s) in MWDI are also not defined in all depth, to be flexible in case something changes on the device data.

We will clarify today, if the filter needs to be narrowed down further

**Comment by ThomasSeitz** [comment]
Fields filter shall not be changed.
