### ISSUE TITLE
timestamp is missing in request-body of ServiceRequestCausesLoggingRequest

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/NetworkDataLakeProxy#52]
As per 2.1.2, the attribute "timestamp" shall be present in request-body of the callback ServiceRequestCausesLoggingRequest. 

This is missing. Shall be updated to https://github.com/openBackhaul/NetworkDataLakeProxy/blob/develop/spec/NetworkDataLakeProxy.yaml

**Comment by kmohr-soprasteria** [comment]
timestamp:
                          type: string
                          description: 'Date and time when [application-name] sent response to [originator]; only to be provided, if [/core-model-1-4:control-construct/logical-termination-point=xx-1-0-0-op-c-bs-eatl-2-1-2-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/detailed-logging-is-on] == true'

**Comment by ThomasSeitz** [comment]
@IswaryaaS 
The attribute "timestamp" is already in the body of the callback.
I looked in the ApplicationPattern.yaml and found the attribute timestamp as 'required'.
I added this attribute and commited it:
Could you please check this issue again?


                  application/json:
                    schema:
                      type: object
                      required:
                        - x-correlator
                        - trace-indicator
                        - user
                        - originator
                        - application-name
                        - release-number
                        - operation-name
                        - response-code
                        - timestamp

**Comment by IswaryaaS** [comment]
Yes, I meant to include the attribute "timestamp" in required section of the callback.
Sorry for missing to detail that part in the description. 
@ThomasSeitz , Thanks for understanding
